source 'http://rubygems.org'

gem 'rails', '~> 4.0.0.rc1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'oauth2-provider', :path => '../..'
